# syntax=docker/dockerfile:1
FROM python:3.10-alpine

WORKDIR /app
COPY ./deploy.py /app/
COPY ./lambdas /app/lambdas/
COPY ./requirements.txt /app/

# Install packages
RUN apk add zip
RUN apk add curl
RUN apk add jq

# Install python dependencies
RUN pip install -r requirements.txt

# Make deploy script executable
RUN chmod +x deploy.py

# This line runs the deploy script upon running the container
CMD ["deploy.py"]

# alpine only has sh, no bash
ENTRYPOINT ["python"]